spring.application.name=LifeLinkBackend
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lifelink
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Load fake data
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:fake_data.sql

# Swagger configuration
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true

server.servlet.context-path=/api

spring.datasource.hikari.initialization-fail-timeout=-1
spring.sql.init.continue-on-error=true

# Encoding configuration
spring.jpa.properties.hibernate.connection.characterEncoding=utf-8
spring.jpa.properties.hibernate.connection.CharSet=utf-8
spring.jpa.properties.hibernate.connection.useUnicode=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# JWT configuration
jwt.secret=Wgo9PuRaHunYaqU3xW/EnxGr35H6hQZO7wcOjeRkENvKOAplc67G8kmX4F1SCmniiJIEcAaYQlrY4045+aF3cw==
jwt.expiration=86400000

# eSignet keys (replace with your generated keys)
PRIVATE_KEY_JWK={"kty":"RSA","n":"xWVg7Rg5mTFn8xJmoct_SHHwgnq3GN94oS3oGUtlUT_7PSJ3gtUQsk653uKYIee_R5VXv_PFUryqewctN9x40DiqBZ-0HAV2IwvheyhNi-_S2QO4a4PNUNCKFb4cme0bmYp8NcEJMjR5b4-5VRDLHgE6LGGo8_xRvhmDO40c92IXGFF8ozxm4PmUkQ7-yjEgHXMp4rZe3ZHFoJ8J8AczD3psIKVA8ZSgzQEdMu80w4LXnIbpXhJB_VHVQONlbhNwVXMV3raWkE9cAQcBCIHqkOCVxr6BX4f1Rd8hRmOPnQ1JP9UeX_KX5cVT4VANjpCoueH7KaXSCSQV7PATQTS9ww","e":"AQAB","d":"fO4hHtezlNMoWrXcqZ5axo8LmisYMP8xhzLvjvFHG8aqDgkRfNasTdYRyVGeykAd2nE8eVftRMgc70jAJ_QIE9USXiF8NboXRpPRrMsRAnyztbeP2B9erwlcf4pRkk6ynsws4qjjQOO7QPBMv2uSYQs8oYAfeQeIzlcTGf1h6dNNZ1fLZ-BLLVV4vGow2eNVHJ_1Ck5k-uChcXKJ2D-9esmKtJ7DYQoEvvcIgFUrFuA0cZmttzoJAva-KdC1XGmk6zrF3eAANZM6E6-DS5470HppUBGQIcM6HJ2ociMNHTaJTUaPhZLiEvICOHap7f_-Vjl96dEWAIBU7eoP7YQV","p":"8YqHla_17IW7UMb8ptbB41M5ExMgpfQjN6ovCV_zLIEt4Av46uB00uMAhgUiwYhbTxaOQAelwwmfLnmkseqVdeEjEUZcdQ9XhzwApthljY3LMlYmdFjNiIWjDuvktW9Bpyjo0Wc9_9g3ZB8uIEPTgS1UlsEaXvDsNVIrF51BNHc","q":"0TZaGg8c0vnhyvY1wHGVw-T11iNd2H8wJr0MU6r-HtgFSwJhxWFtJzkxQ-dWjK-vYytvg5iyRo9ZDKruVp31bs0Ea-gs-NV0eOVX4Capcai6IO29zngbTKFb23qngT3A-XOo3dokoeIZ0SBXxFwxo1a5nCJuybT1puZ31D4MEBU","dp":"II38QjeKHMvVeEipis8NKNdxrNl6IAPsrzb3yfqtqsTqavUSIo4IENhZnLaafZ0kOV-f4o9lTwk_9CKfCP_GDzI96LkkAv8DXA3BRLuLzG1dArbLzgieAxWH6Z3voGiTX7VK09Zna9E3ff4Z2G1r11BFw1_ZbwxnubQObMtcG3c","dq":"Rl4MojUxEbkge96iJ69Mm034beUJXJcy_-SYL9AUlxU7eoY7kmL5jrbK3jcCQmGZETb70_xZAiiW4A7iCVopwfHNKeo2rh9FhKBHFUqLtYH10LuGGtsE-5pORh0UGAFIVd7UDoKfzZ855cAGJTKJM5Io7d4a-1cVROTBqy6Pah0","qi":"8WUe0PK7PqewoPaTpDotcQUcuL4yktBWhTFiUwHkjgelifqa4CaHc0ahwguwRoJsCOLDpLJVlA9uRFOVsXaFcKFr5ozTR0Nqiz_T_GIafijXF5GIyAGi0rtUASxuTz6IPHDaO3kw1ZSGcddeiJFlue4jCaGaWsh59TsmpukAQPQ"}
CLIENT_ID=IBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxWVg7R